<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.dAV6Gxa' shared service.

return $this->privates['.service_locator.dAV6Gxa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\ApiController::jsonEncodeUser' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\ApiController::postGetUserAction' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\ApiController::postUpdateUserAction' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\ApiController::setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\RegisterController::register' => ['privates', '.service_locator.8iM9AO_', 'get_ServiceLocator_8iM9AOService.php', true],
    'App\\Controller\\RegisterController::updateUser' => ['privates', '.service_locator.aYpk5zP', 'get_ServiceLocator_AYpk5zPService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\ApiController:jsonEncodeUser' => ['privates', '.service_locator.wypGnUQ', 'get_ServiceLocator_WypGnUQService.php', true],
    'App\\Controller\\ApiController:postGetUserAction' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\ApiController:postUpdateUserAction' => ['privates', '.service_locator.kvRz10W', 'get_ServiceLocator_KvRz10WService.php', true],
    'App\\Controller\\ApiController:setViewHandler' => ['privates', '.service_locator.l2alLEu', 'get_ServiceLocator_L2alLEuService.php', true],
    'App\\Controller\\RegisterController:register' => ['privates', '.service_locator.8iM9AO_', 'get_ServiceLocator_8iM9AOService.php', true],
    'App\\Controller\\RegisterController:updateUser' => ['privates', '.service_locator.aYpk5zP', 'get_ServiceLocator_AYpk5zPService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\ApiController::jsonEncodeUser' => '?',
    'App\\Controller\\ApiController::postGetUserAction' => '?',
    'App\\Controller\\ApiController::postUpdateUserAction' => '?',
    'App\\Controller\\ApiController::setViewHandler' => '?',
    'App\\Controller\\RegisterController::register' => '?',
    'App\\Controller\\RegisterController::updateUser' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\ApiController:jsonEncodeUser' => '?',
    'App\\Controller\\ApiController:postGetUserAction' => '?',
    'App\\Controller\\ApiController:postUpdateUserAction' => '?',
    'App\\Controller\\ApiController:setViewHandler' => '?',
    'App\\Controller\\RegisterController:register' => '?',
    'App\\Controller\\RegisterController:updateUser' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
