<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8iM9AO_' shared service.

return $this->privates['.service_locator.8iM9AO_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'passwordEncoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService.php', true],
    'vehicleClassRepository' => ['privates', 'App\\Repository\\VehicleClassRepository', 'getVehicleClassRepositoryService.php', true],
], [
    'passwordEncoder' => '?',
    'vehicleClassRepository' => 'App\\Repository\\VehicleClassRepository',
]);
