<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYdxC0mj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYdxC0mj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYdxC0mj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYdxC0mj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYdxC0mj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YdxC0mj',
    'container.build_id' => 'd959d5f3',
    'container.build_time' => 1565241800,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYdxC0mj');
