<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSZ4FfYF\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSZ4FfYF/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSZ4FfYF.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSZ4FfYF\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSZ4FfYF\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SZ4FfYF',
    'container.build_id' => '49457e93',
    'container.build_time' => 1559328367,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSZ4FfYF');
